controllers/ClientController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\imagine\Image;
use app\models\Client;
use app\models\search\ClientSearch;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
		];
	}

	/**
	 * Lists all Client models.
	 *
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new ClientSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		if ($searchModel->cpf) {
			if ($dataProvider->totalCount == 0) {
				return $this->redirect(['create', 'cpf' => $searchModel->cpf]);
			} else if ($dataProvider->totalCount == 1) {
				$model = Client::findIdentityByCpf($searchModel->cpf);

				if ($model) {
					return $this->redirect(['update', 'id' => $model->id]);
				}
			}
		}

		return $this->render('index', ['searchModel' => $searchModel, 'dataProvider' => $dataProvider]);
	}

	/**
	 * Creates a new Client model.
	 * If creation is successful, the browser will be redirected to the 'index' page.
	 *
	 * @return mixed
	 */
	public function actionCreate($cpf = null)
	{
		$model = new Client();

		$model->scenario = 'create';

		if ($model->load(Yii::$app->request->post())) {
			if ($model->save() and $model->createPhotoBig() and $model->createPhotoThumb()) {
				if (!$model->checkin) {
					Yii::$app->session->setFlash('success', 'Cliente cadastrado com sucesso!');
				}

				return $this->redirect(['index']);
			}
		} else {
			$model->cpf = $cpf;
		}

		return $this->render('create', ['model' => $model]);
	}

	/**
	 * Updates an existing Client model.
	 * If update is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		$model->scenario = 'update';

		if ($model->load(Yii::$app->request->post())) {
			if ($model->save()) {
				if ($model->photo) {
					$model->createPhotoBig();
					$model->createPhotoThumb();
				}

				if (!$model->checkin) {
					Yii::$app->session->setFlash('success', 'Cliente atualizado com sucesso!');
				}

				return $this->redirect(['index']);
			}
		}

		return $this->render('update', ['model' => $model]);
	}

	/**
	 * Realiza checkin
	 *
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionCheckin($id)
	{
		$model = $this->findModel($id);

		if ($model->doCheckin()) {
			Yii::$app->session->setFlash('success', 'Checkin realizado com sucesso!');
		}

		return $this->redirect('index');
	}

	/**
	 * Download photo
	 *
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDownload($id)
	{
		$model = $this->findModel($id);

		return Yii::$app->response->sendFile($model::filePath() . '/' . $model->fileName());
	}

	/**
	 * Download photo big
	 *
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDownloadPhotoBig($id)
	{
		$model = $this->findModel($id);

		return Yii::$app->response->sendFile($model::filePath() . '/' . $model->fileNameBig());
	}

	/**
	 * Download photo thumb
	 *
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDownloadPhotoThumb($id)
	{
		$model = $this->findModel($id);

		return Yii::$app->response->sendFile($model::filePath() . '/' . $model->fileNameThumb());
	}

	/**
	 * Deletes an existing Client model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete($id)
	{
		$model = $this->findModel($id);

		if ($model->delete()) {
			Yii::$app->session->setFlash('success', 'Usuário excluído!');
		} else {
			Yii::$app->session->setFlash('error', 'Falha ao excluir usuário!');
		}

		return $this->redirect(['index']);
	}

	/**
	 * Finds the Client model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id
	 * @return Client the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Client::findOne($id)) !== null) {
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\User;
use app\models\search\UserSearch;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
		];
	}

	/**
	 * Lists all User models.
	 *
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new UserSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', ['searchModel' => $searchModel, 'dataProvider' => $dataProvider]);
	}

	/**
	 * Creates a new User model.
	 * If creation is successful, the browser will be redirected to the 'index' page.
	 *
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new User();

		$model->scenario = 'create';

		if ($model->load(Yii::$app->request->post()) and $model->save()) {
			Yii::$app->session->setFlash('success', 'Usuário cadastrado com sucesso!');

			return $this->redirect(['index']);
		}

		return $this->render('create', ['model' => $model]);
	}

	/**
	 * Updates an existing User model.
	 * If update is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		$model->scenario = 'update';

		if ($model->load(Yii::$app->request->post()) and $model->save()) {
			Yii::$app->session->setFlash('success', 'Usuário atualizado com sucesso!');

			return $this->redirect(['index']);
		}

		return $this->render('update', ['model' => $model]);
	}

	/**
	 * Updates own User model.
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionProfile()
	{
		$model = $this->findModel(Yii::$app->user->identity->id);

		$model->scenario = 'profile';

		if ($model->load(Yii::$app->request->post()) and $model->save()) {
			Yii::$app->session->setFlash('success', 'Usuário atualizado com sucesso!');

			return $this->redirect(['/']);
		}

		return $this->render('profile', ['model' => $model]);
	}

	/**
	 * Deletes an existing User model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete($id)
	{
		$model = $this->findModel($id);

		if ($model->delete()) {
			Yii::$app->session->setFlash('success', 'Usuário excluído!');
		} else {
			Yii::$app->session->setFlash('error', 'Falha ao excluir usuário!');
		}

		return $this->redirect(['index']);
	}

	/**
	 * Finds the User model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id
	 * @return User the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = User::findOne($id)) !== null) {
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}
}

views/layouts/main.php
<?php

/**
 * @var $this \yii\web\View
 * @var $content string
 */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);

$this->registerJs("
	$('[data-toggle=\"tooltip\"]').tooltip();
	$('[data-toggle=\"popover\"]').popover();
");

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<?= Html::csrfMetaTags() ?>

	<link rel="shortcut icon" href="<?= Yii::$aliases['@web']; ?>/favicon.ico">

	<title><?= Html::encode($this->title) ?> | <?= Yii::$app->name ?></title>

	<?php $this->head() ?>
</head>
<body>
	<?php $this->beginBody() ?>

	<div class="wrap">
		<?php
			NavBar::begin([
				'brandLabel' => Yii::$app->name,
				'brandUrl' => Yii::$app->homeUrl,
				'options' => [
					'class' => 'navbar-inverse',
				],
			]);

			echo Nav::widget([
				'options' => ['class' => 'navbar-nav navbar-right'],
				'items' => [
					['label' => 'Clientes', 'url' => ['/client/index'], 'visible' => !Yii::$app->user->isGuest],
					['label' => 'Usuários', 'url' => ['/user/index'], 'visible' => !Yii::$app->user->isGuest],
					Yii::$app->user->isGuest
						? ['label' => 'Login', 'url' => ['/site/login']]
						: ['label' => Yii::$app->user->identity->name, 'url' => '#', 'items' => [
							['label' => 'Perfil', 'url' => ['user/profile']],
							['label' => 'Logout', 'url' => ['site/logout'], 'linkOptions' => ['data' => ['method' => 'post', 'confirm' => 'Deseja realmente sair?']]],
						]],
				],
			]);

			NavBar::end();
		?>

		<div class="container">
			<?= Breadcrumbs::widget(['homeLink' => ['label' => '<i class="glyphicon glyphicon-home"></i>', 'url' => ['/']], 'encodeLabels' => false, 'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []]) ?>
			<?= Alert::widget() ?>
			<?= $content ?>
		</div>
	</div>

	<footer class="footer">
		<div class="container">
			<p><?= Yii::$app->name ?> &copy; <?= date('Y') ?></p>
		</div>
	</footer>

	<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>